### PR TITLE
Issue541 responsiveness

### PR DESCRIPTION
**Pull request by wd15**
Improve responsiveness of mostly every page other than pages generated by notebooks.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/559)

### CODE REVIEW

**Comment by tkphd** [comment]
Generally, it still looks OK, but some of the images behave badly (truncating rather than scaling), e.g. 
chimad_responsive_bug

**Comment by wd15** [comment]
@tkphd: the T-shaped image is in a notebook and they are not responsive currently. I have a vague notion to move the benchmark specs out of notebooks into regular web pages at some point, but that won't happen for some time.

**Comment by tkphd** [comment]
Gotcha, OK.

**Comment by tkphd** [comment]
Confirmed on my mobile -- benchmark results graphs and tables look much better. Navigating the page can be tricky, since swiping sometimes pans the graph instead of scrolling, which is a new usability issue but easily worked around.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[_includes/benchmarks.html, line 95 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/559#-L-I4ai_PzYRL_hERPSS:-L-I4aiaJO1Zmsp2dQ8M:bkt620g) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/d5031f979e43926049049f1aa0f17a22faf88111/_includes/benchmarks.html#L95)):*
Forgive my ignorance, but what is the functional significance of changing 
>  `<div class="col s8 offset-s2">`
to
> `<div class="col s12 m12 l12 xl10 offset-xl2"`
?

Was the older version defining only the "small" size with 8 columns, while we now have `s`, `m`, `l` at 12 columns and `xl` at 10 columns, with an offset only on `xl` of 2 columns? What effect does this have on the displayed data?

Is 12 a magic number, empirically chosen on some device?

---

*[js/data_table.coffee, line 30 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/559#-L-I6yP63NTrWh-BVxUn:-L-I624T-MAfcixqWbGj:b-1k1qv3) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/d5031f979e43926049049f1aa0f17a22faf88111/js/data_table.coffee#L30)):*
> ```CoffeeScript
> 
>   data = {
>     responsive: true
> ```

As @guyer mentioned, is `responsive: true` necessary? It's unclear how/where this statement is used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/559#-:-L-I3xg2RHwAuj8j3L4r:bq3qofi)*

**Comment by wd15** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[_includes/benchmarks.html, line 95 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/559#-L-I4ai_PzYRL_hERPSS:-L-I8Oi7fVPdOnBFArMT:bvnui2a) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/d5031f979e43926049049f1aa0f17a22faf88111/_includes/benchmarks.html#L95)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Forgive my ignorance, but what is the functional significance of changing 
>  `<div class="col s8 offset-s2">`
to
> `<div class="col s12 m12 l12 xl10 offset-xl2"`
?

Was the older version defining only the "small" size with 8 columns, while we now have `s`, `m`, `l` at 12 columns and `xl` at 10 columns, with an offset only on `xl` of 2 columns? What effect does this have on the displayed data?

Is 12 a magic number, empirically chosen on some device?
</blockquote></details>

The effect is to make it responsive so if you view the page at the different screen resolutions as defined by s, m, l and xl then you get a different looking page. The letters refer to the resolution and the numbers refer to the number of subcolumns within the row that you want `col` to use.

The number 12 is the maximum number of sub-columns a given row can be divided into.

See http://materializecss.com/grid.html for more details.

---

*[js/data_table.coffee, line 30 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/559#-L-I6yP63NTrWh-BVxUn:-L-IAIeXV06aMVmSfQ4u:bnojfjt) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/d5031f979e43926049049f1aa0f17a22faf88111/js/data_table.coffee#L30)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

As @guyer mentioned, is `responsive: true` necessary? It's unclear how/where this statement is used.
</blockquote></details>

It makes Datatables responsive if you switch it to `false` you should get different behavior. See https://datatables.net/extensions/responsive/.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/559)*

**Pull request merged**
