### PR TITLE
Update notebooks to overcome Travis test failures

### PR DESCRIPTION
**Pull request by wd15**
Address #185

### CODE REVIEW

**Comment by tkphd** [comment]
It builds and looks OK, so I am prepared to merge. For 7960052, would specifying the kernel ([source](https://github.com/Anaconda-Platform/nb_conda_kernels/issues/34#issuecomment-231224187)) resolve this without excluding the notebooks from testing?

**Comment by wd15** [comment]
Wait then, I'll try that. I did see that issue, but I didn't read it very carefully. Wait on this for now.

**Comment by wd15** [comment]
I changed the name of the Python kernel and it seemed to work. This can be merged now.

**Comment by tkphd** [comment]
That seems better. Thanks!

**Pull request merged**
