### PR TITLE
Add "Upload Benchmark Results" ribbon

### PR DESCRIPTION
**Pull request by wd15**
Address #483

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/518)

### CODE REVIEW

**Comment by wd15** [comment]
@guyer, assigning you to this as you requested the "fork me on github" style banner for website.

**Comment by tkphd** [comment]
The banner works, so the code is fine. But the black ([`#000`](http://www.colorhexa.com/000000)) ribbon clashes bigtime with the pastel green ([`#9ccc65`](http://www.colorhexa.com/9ccc65)) decor of the site. Can we choose another -- perhaps [`#9565cc`](http://www.colorhexa.com/9565cc), which is the complement to [`#9ccc65`](http://www.colorhexa.com/9ccc65)?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/518#-:-KxToIG4pYVkzPZdio5d:b-jtncrb)*

**Comment by wd15** [comment]
@tkphd, I used colors from the Materialize palette that were close to the ones you suggested, http://materializecss.com/color.html

**Comment by tkphd** [comment]
LGTM

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/518#-:-KxUIzRy_h_xqzOzeLhj:bb6ywmx)*

**Comment by tkphd** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/518)*

**Pull request merged**
