### PR TITLE
Improve upload instructions

### PR DESCRIPTION
**Pull request by wd15**
Address #180

The YAML documentation was sorely lacking and needs to be improved.

 - Add links to YAML documentation.

 - Ensure that the minimal example is tested.

### CODE REVIEW

**Comment by tkphd** [comment]
Unless I'm building it wrong, this renders the minimal example `meta.yaml` in a concatenated jumble without any formatting. That is not acceptable.

**Comment by wd15** [comment]
Do other pages with code such as DEVELOPMENT.md render correctly for you? No code blocks are rendering correctly for me after I updated my version of Jekyll on my laptop although my desktop and pages.nist.gov still works correctly. 

I'm just wondering if there is something wrong with that specific code block (with YAML) or are all code blocks broken on your version of Jekyll.

**Comment by tkphd** [comment]
UGH. You're right, it's jekyll, not us.

**Comment by tkphd** [comment]
Looks good on jekyll v.3.3.1. Merging.

**Pull request merged**
