### PR TITLE
Issue520 benchmark spec table

### PR DESCRIPTION
**Pull request by wd15**
Address #520 

Implement a table of all benchmarks including older revisions. The table appears in `benchmark/table ` and at the top of all the benchmark specs.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/537)

### CODE REVIEW

**Comment by wd15** [comment]
@amjokisaari, if you are interested in reviewing this pull request and do find the time then please do contact me regarding how to fire on the website on your own computer - the [development guide](https://pages.nist.gov/chimad-phase-field/DEVELOPMENT/) should help - or how to review a pull request if you're not familiar with the process.

**Comment by tkphd** [comment]
Jekyll throws `ERROR '/chimad-phase-field/js/benchmark_data_table.js' not found.`, even after deleting `_site` and rebuilding. I have `js/benchmark_data_table.coffee`, but no js version. Am I missing a dependency, or a build command?

**Comment by wd15** [comment]
On Wed, Nov 8, 2017 at 1:50 PM, Trevor Keller <notifications@github.com> wrote:
>
> Jekyll throws ERROR '/chimad-phase-field/js/benchmark_data_table.js' not found., even after deleting _site and rebuilding. I have js/benchmark_data_table.coffee, but no js version. Am I missing a dependency, or a build command?

No, the jekyll-coffeescript add-on translates Coffeescript into
Javascript as part of the jekyll build. Is there a
benchmark_data_table.js file anywhere in the _site directory?

>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.




-- 
Daniel Wheeler

**Comment by tkphd** [comment]
My dependencies were out of date. Sorted now; will review this PR tomorrow.

**Comment by tkphd** [comment]
Reviewed 30 of 33 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[_includes/coffee/essential.coffee, line 8 at r2](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/537#-KyXCPQqVRsJXf8qUg5z:-KyXCPQqVRsJXf8qUg6-:b-6uupi7) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/32892855d8a3109e3acd25f2f4124f13d0dd7fd2/_includes/coffee/essential.coffee#L8)):*
> ```CoffeeScript
> ###
> 
> # Core
> ```

Are the commented-out lines and functions still useful?

---

*[_includes/coffee/main.coffee, line 1 at r2](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/537#-KyXCfkP-LQTTLcidEyA:-KyXCfkP-LQTTLcidEyB:bthhtrb) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/32892855d8a3109e3acd25f2f4124f13d0dd7fd2/_includes/coffee/main.coffee#L1)):*
> ```CoffeeScript
> ### General functions that don't update the DOM
> ```

What's a DOM?

---

*[_includes/coffee/uploads.coffee, line 1 at r2](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/537#-KyXCvMxousWkAL7nrd2:-KyXCvMxousWkAL7nrd3:bthhtrb) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/32892855d8a3109e3acd25f2f4124f13d0dd7fd2/_includes/coffee/uploads.coffee#L1)):*
> ```CoffeeScript
> ### Update the DOM for the benchmark uploads
> ```

What's a DOM?

---

*[_includes/coffee/uploads.coffee, line 2 at r2](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/537#-KyXCx6guWz36F2lB0ev:-KyXCx6guWz36F2lB0ew:b-2euf8a) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/32892855d8a3109e3acd25f2f4124f13d0dd7fd2/_includes/coffee/uploads.coffee#L2)):*
> ```CoffeeScript
> ### Update the DOM for the benchmark uploads
> ###
> ```

Are these octothorpes necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/537)*

**Comment by wd15** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[_includes/coffee/essential.coffee, line 8 at r2](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/537#-KyXCPQqVRsJXf8qUg5z:-KyXSsOzCRsW7bGDkRmp:b-ty7k6v) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/32892855d8a3109e3acd25f2f4124f13d0dd7fd2/_includes/coffee/essential.coffee#L8)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Are the commented-out lines and functions still useful?
</blockquote></details>

Yes, they are directives for the Coffeescript linter.

---

*[_includes/coffee/main.coffee, line 1 at r2](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/537#-KyXCfkP-LQTTLcidEyA:-KyXT4WnmINJ2Po9HbT_:bt802aw) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/32892855d8a3109e3acd25f2f4124f13d0dd7fd2/_includes/coffee/main.coffee#L1)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

What's a DOM?
</blockquote></details>

The data object model, https://en.wikipedia.org/wiki/Document_Object_Model

---

*[_includes/coffee/uploads.coffee, line 1 at r2](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/537#-KyXCvMxousWkAL7nrd2:-KyXTIDjjJ_x64ZX6Kk-:bt802aw) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/32892855d8a3109e3acd25f2f4124f13d0dd7fd2/_includes/coffee/uploads.coffee#L1)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

What's a DOM?
</blockquote></details>

The data object model, https://en.wikipedia.org/wiki/Document_Object_Model

---

*[_includes/coffee/uploads.coffee, line 2 at r2](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/537#-KyXCx6guWz36F2lB0ev:-KyXTTfdWa5XSzbqqwJT:b-6apgeo) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/32892855d8a3109e3acd25f2f4124f13d0dd7fd2/_includes/coffee/uploads.coffee#L2)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Are these octothorpes necessary?
</blockquote></details>

Not strictly in this case, but I'm using the following formatting for modules and functions

```
### short header

longer text

Args:

Returns:

Tags:
###
```

The `###` are like `"""` in Python.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/537)*

**Pull request merged**
