### PR TITLE
Issue568 surge

### LINKED ISSUE #568: Deploy website using Surge for all pull requests
e.g., with Travis' deploy options, https://docs.travis-ci.com/user/deployment/ ?
Looks like others have considered this path as well: https://medium.com/onfido-tech/travis-surge-github-auto-deploy-every-pr-branch-and-tag-a6c8c790831f . But this is reaching outside my comfort zone.
Oh, huh. That post uses https://surge.sh/, which may be just the service we're looking for?

### PR DESCRIPTION
**Pull request by wd15**
**Add Surge support**

Fixes #568 

 - Add surge support in .travis.yml
 - Add a PULL_REQUEST_TEMPLATE to reference the link to Surge

## Reason

Support Surge to make the review process easier.

## Changes

Add surge support in .travis.yml

## Side Effects

The Surge token is out in the open right now, not worried though

## Review Process

Website should be available at http://random-cat-595.surge.sh.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/595)

### CODE REVIEW

**Comment by tkphd** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[PULL_REQUEST_TEMPLATE, line 1 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595#-L0G5XIGKx34W7MU1aCT:-L0G5XIGKx34W7MU1aCU:b-bzm9j9) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/378f5d3db2b7ef11c161912cd6db0f6c79cfb4d9/PULL_REQUEST_TEMPLATE#L1)):*
> ```
> **Short description**
> ```

Consider placing in a `.github` folder

---

*[PULL_REQUEST_TEMPLATE, line 2 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595#-L0G5_wVwIrFlv4BkvJ3:-L0G5_wVwIrFlv4BkvJ4:b-qcz7ez) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/378f5d3db2b7ef11c161912cd6db0f6c79cfb4d9/PULL_REQUEST_TEMPLATE#L2)):*
Re-phrase as a simple template (less formal):

> ## Proposal to Change PFHub Website
>
> The proposed changes are intended to {summary of intent}.
>
> Fixes #, Addresses #
>
> This is achieved by {description of method}.
>
> This may have unintended consequences in {areas of concern}.
>
> The code has been checked for implementation and typographical errors on a {local build | Travis-CI | `http://random-cat-{pull-request number}.surge.sh`}
> It causes changes to the following content:
> - list
> - of changed
> - webpages
> 
> The authors request closer inspection from @pfhub-devs, @wd15

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595)*

**Comment by wd15** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[PULL_REQUEST_TEMPLATE, line 1 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595#-L0G5XIGKx34W7MU1aCT:-L0GTwZfGrj7QMhrXIo0:bb6un1j) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/378f5d3db2b7ef11c161912cd6db0f6c79cfb4d9/PULL_REQUEST_TEMPLATE#L1)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Consider placing in a `.github` folder
</blockquote></details>

Done

---

*[PULL_REQUEST_TEMPLATE, line 2 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595#-L0G5_wVwIrFlv4BkvJ3:-L0GU7Ee_wsPr1wKNFKK:b44xm38) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/378f5d3db2b7ef11c161912cd6db0f6c79cfb4d9/PULL_REQUEST_TEMPLATE#L2)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Re-phrase as a simple template (less formal):

> ## Proposal to Change PFHub Website
>
> The proposed changes are intended to {summary of intent}.
>
> Fixes #, Addresses #
>
> This is achieved by {description of method}.
>
> This may have unintended consequences in {areas of concern}.
>
> The code has been checked for implementation and typographical errors on a {local build | Travis-CI | `http://random-cat-{pull-request number}.surge.sh`}
> It causes changes to the following content:
> - list
> - of changed
> - webpages
> 
> The authors request closer inspection from @pfhub-devs, @wd15
</blockquote></details>

I simplified it even more. The last line asking for closer inspection is not required as that what happens when devs are selected for review anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595)*

**Comment by tkphd** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[PULL_REQUEST_TEMPLATE, line 2 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595#-L0G5_wVwIrFlv4BkvJ3:-L0HskwSsUh9BOL4jf37:brlz1r0) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/378f5d3db2b7ef11c161912cd6db0f6c79cfb4d9/PULL_REQUEST_TEMPLATE#L2)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

I simplified it even more. The last line asking for closer inspection is not required as that what happens when devs are selected for review anyway.
</blockquote></details>

Full sentences are preferable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595)*

**Comment by tkphd** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[PULL_REQUEST_TEMPLATE, line 2 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595#-L0G5_wVwIrFlv4BkvJ3:-L0HtFxsEYiJWvOkoYtO:b81lnhw) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/378f5d3db2b7ef11c161912cd6db0f6c79cfb4d9/PULL_REQUEST_TEMPLATE#L2)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Full sentences are preferable.
</blockquote></details>

... otherwise, looks good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595)*

**Comment by wd15** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[PULL_REQUEST_TEMPLATE, line 2 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595#-L0G5_wVwIrFlv4BkvJ3:-L0KqBEigXZ6DyDtz9Z6:b-bd52mu) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/378f5d3db2b7ef11c161912cd6db0f6c79cfb4d9/PULL_REQUEST_TEMPLATE#L2)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

... otherwise, looks good.
</blockquote></details>

Now using full sentences

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595)*

**Comment by tkphd** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[PULL_REQUEST_TEMPLATE, line 2 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595#-L0G5_wVwIrFlv4BkvJ3:-L0L4UL0q-oib94rR6ls:b-t0ygk0) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/378f5d3db2b7ef11c161912cd6db0f6c79cfb4d9/PULL_REQUEST_TEMPLATE#L2)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

Now using full sentences
</blockquote></details>

My original would involve less deletion of boilerplate for the end-user, but this is a question of style rather than quality. Drop the curly braces and merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/595)*

**Pull request merged**
