### PR TITLE
Issue567 benchmark 4

### PR DESCRIPTION
**Pull request by wd15**
Benchmark 4 specification notebook

If you can't set up this site locally, you can view the notebook on Github at https://github.com/wd15/chimad-phase-field/blob/issue567-benchmark-4/benchmarks/benchmark4.ipynb. Not exactly the same as on the website, but at least renders the equations.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/592)

### CODE REVIEW

**Comment by tkphd** [comment]
Reviewed 21 of 23 files at r1.
Review status: 21 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[_data/benchmarks.yaml, line 58 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/592#-L06XJ9kKC9Y8qBnH9Vm:-L06XJ9kKC9Y8qBnH9Vn:bkm50w1) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/4ff4a0b3f21e35b545f1bf962383e82128c9b331/_data/benchmarks.yaml#L58)):*
> https://www.overleaf.com/read/xwzkbzzwcyqy

Overleaf is not the best service for sharing documents. An arXiv or researchgate link would be better, if available, if not the publisher's page for it. Coordinate with authors.

---

*[_data/benchmarks.yaml, line 82 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/592#-L06Yk73ojbNg7jvLpxj:-L06Yk73ojbNg7jvLpxk:b-v24in9) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/4ff4a0b3f21e35b545f1bf962383e82128c9b331/_data/benchmarks.yaml#L82)):*
> ```YAML
>       event:
>         name: Publication 2
>         url: "https://www.overleaf.com/read/xwzkbzzwcyqy"
> ```

Overleaf is not the best service for sharing documents. An arXiv or researchgate link would be better, if available, if not the publisher's page for it. Coordinate with authors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/592)*

**Comment by tkphd** [comment]
Review status: 21 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[simulations/4a.1.html, line 5 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/592#-L06_MTPB9uWBYC3C7EX:-L06_MTPB9uWBYC3C7EY:b4eresz) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/4ff4a0b3f21e35b545f1bf962383e82128c9b331/simulations/4a.1.html#L5)):*
> ```HTML
> ---
> 
> {% assign benchmark_id = page.url | replace: '/simulations/', '' | replace: '/' '' %}
> ```

Please use 
```
{% assign benchmark_id = page.url | remove: '/simulations/' | remove: '/' %}
```
as a template to avoid Liquid syntax warnings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/592)*

**Comment by tkphd** [comment]
Parameters table renders exponents strangely:
param_table

**Comment by wd15** [comment]
@tkphd,  I can't make it display as you have it above.  Is that after you resized the browser? Try hitting reload.

**Comment by wd15** [comment]
@tkphd, that seems to be the github rendering of the table, don't worry about that.

**Comment by tkphd** [comment]
No, the screen cap was taken on my local build of the site, not on GitHub. Many exponents are wrapped onto second lines in table cells.

**Comment by wd15** [comment]
@tkphd, the table should be fixed now

**Comment by tkphd** [comment]
Yep, table looks better. Passes visual muster; the benchmark authors should check technical merits.

**Pull request merged**
