### PR TITLE
Issue411 guyer ux

### PR DESCRIPTION
**Pull request by wd15**
Addresses #411 

Address a number of issues raised by Jon Guyer that simplifies the layout of the site. Some of the issues that Jon raised have been deferred, but the central issue regarding merging simulations and benchmarks has been addressed.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/516)

### CODE REVIEW

**Comment by tkphd** [comment]
:lgtm:

---

Reviewed 48 of 48 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[ABOUT.md, line 47 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxEquZDTO4ESZ4Z6To-:-KxEquZDTO4ESZ4Z6To0:b5p2mi3) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/ABOUT.md#L47)):*
> ```Markdown
> <h4> Code of Conduct </h4>
> 
> We have a code of conduct and take it very seriously. Please the [code
> ```

- Replace "take it very seriously" with "enforce it in our online interactions and codebase."
- "Please see the..." (missing a word)

---

*[ABOUT.md, line 62 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxErOxTkPcYp_TFOTI_:-KxErOxTkPcYp_TFOTIa:bd75i8y) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/ABOUT.md#L62)):*
> ```Markdown
> <h5> Which code should I use to solve my phase field problem? </h5>
> 
> We don't have the answer to this question yet, but we are working on
> ```

I find this misleading: we are not really working to pick a winner.
Perhaps rephrase as "the right code for you depends on your
familiarity with phase-field methods and software, particular hardware
you intend to use, and complexity of your equations of motion and
mesh geometry. We have a list..."

---

*[codes.html, line 5 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxEsJLSQ1GJkx_swRZm:-KxEsJLSQ1GJkx_swRZn:boud3x9) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/codes.html#L5)):*
> ```HTML
> layout: collection
> comment: >-
>   Codes with well documented, annotated examples that demonstrate the
> ```

Who chooses which codes are recommended and which are not?

---

*[CONTACT.md, line 1 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxEsgHF3tP0I5d2kg3K:-KxEsgHF3tP0I5d2kg3L:bswk8ht) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/CONTACT.md#L1)):*
> ```Markdown
> ---
> ```

Where does this content show up?

---

*[submit_a_new_code.md, line 6 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxEsygCA9mcvcuzNLJz:-KxEsygCA9mcvcuzNLK-:b-9aakhu) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/submit_a_new_code.md#L6)):*
> ```Markdown
> comment: >-
>   How to submit a code to the list of <a
>   href="/chimad-phase-field/codes">suggest codes</a>
> ```

suggested

---

*[simulations/index.html, line 29 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxEu8TgzowZxJ-alEBq:-KxEu8TgzowZxJ-alEBr:bx98yzq) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/simulations/index.html#L29)):*
> ```HTML
>              href="/chimad-phase-field/simulations/upload_form"
>              target="_blank">
>             Upload a New Benchmark Result
> ```

Oh, that's much better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-:-KxEuTjA6OzmNgvH-N3N:bnfp4nl)*

**Comment by guyer** [comment]
*[ABOUT.md, line 62 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxErOxTkPcYp_TFOTI_:-KxIqJwW3jPxfd-zX18k:b-p8lnpd) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/ABOUT.md#L62)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

I find this misleading: we are not really working to pick a winner.
Perhaps rephrase as "the right code for you depends on your
familiarity with phase-field methods and software, particular hardware
you intend to use, and complexity of your equations of motion and
mesh geometry. We have a list..."

</blockquote></details>

"Our objective is that the benchmark results will help illustrate which codes are suited to which problems, but the judgement is ultimately yours."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by guyer** [comment]
*[CODE_OF_CONDUCT.md, line 98 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxIsFQEJW2D8ngIVw-u:-KxIsFQEJW2D8ngIVw-v:b-oe528r) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/CODE_OF_CONDUCT.md#L98)):*
> <daniel.wheeler@nist.gov>

By and large, addresses like this shouldn't be to an individual person. I don't know that it should be devops (but I don't think it's a disaster if it is. They'll route appropriately.)  It shouldn't be hard to set up a <chimad-phasefield-admin@nist.gov> remailer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by guyer** [comment]
*[CODE_OF_CONDUCT.md, line 97 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxIsZDddGhJp7KmK9Yl:-KxIsZDe03DM422uUld4:b-4pr93c) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/CODE_OF_CONDUCT.md#L97)):*
> NIST GitHub

Should it be called this? "CHiMaD Phase Field moderator"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by guyer** [comment]
*[CODE_OF_CONDUCT.md, line 110 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxIshSTH-R-hoIqT9Id:-KxIshSTH-R-hoIqT9Ie:b-vd2cjc) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/CODE_OF_CONDUCT.md#L110)):*
> NIST GitHub moderator at
> <daniel.wheeler@nist.gov>

As above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by guyer** [comment]
*[codes.html, line 5 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxEsJLSQ1GJkx_swRZm:-KxIsslAzyuN9olBHd92:b-y083x5) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/codes.html#L5)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Who chooses which codes are recommended and which are not?
</blockquote></details>

We do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by guyer** [comment]
*[INVOLVEMENT.md, line 9 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxItSFPU5YFcXGo3DQM:-KxItSFPU5YFcXGo3DQN:b-mxnff8) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/INVOLVEMENT.md#L9)):*
> involving

delete

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by guyer** [comment]
*[INVOLVEMENT.md, line 11 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxIt_iX8Xw-9MaS8trv:-KxIt_iX8Xw-9MaS8trw:bo50lwz) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/INVOLVEMENT.md#L11)):*
> .

:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by guyer** [comment]
*[_includes/navbar.html, line 6 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxIv0MiK0FcpvjiDVC-:-KxIv0MiK0FcpvjiDVC0:bi3jfg) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/_includes/navbar.html#L6)):*
> Suggested Codes

Suggest a Code (?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by guyer** [comment]
*[_includes/navbar.html, line 49 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxIvFbdgQhbVEz2L7Pm:-KxIvFbdgQhbVEz2L7Pn:bi3jfg) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/_includes/navbar.html#L49)):*
> Suggested Codes

Suggest a Code (?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by guyer** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[ABOUT.md, line 18 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxIpjq4KwngkzsdrALI:-KxIpjq4KwngkzsdrALJ:b-p8k8p5) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/ABOUT.md#L18)):*
> and by

Not grammatical. delete.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by wd15** [comment]
Review status: 43 of 47 files reviewed at latest revision, 14 unresolved discussions.

---

*[ABOUT.md, line 18 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxIpjq4KwngkzsdrALI:-KxJNDJH2iTg7ZvyAZGh:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/ABOUT.md#L18)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by wd15** [comment]
Review status: 43 of 47 files reviewed at latest revision, 14 unresolved discussions.

---

*[CODE_OF_CONDUCT.md, line 98 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxIsFQEJW2D8ngIVw-u:-KxJNHGRsv4wv3qonMmJ:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/CODE_OF_CONDUCT.md#L98)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

Changed back to devops@nist.gov, but will address with https://github.com/usnistgov/chimad-phase-field/issues/524
</blockquote></details>

Done.

---

*[CODE_OF_CONDUCT.md, line 110 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxIshSTH-R-hoIqT9Id:-KxJNIMKFLF_mBvJG_FZ:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/CODE_OF_CONDUCT.md#L110)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

Changed back to devops@nist.gov, but will address with https://github.com/usnistgov/chimad-phase-field/issues/524
</blockquote></details>

Done.

---

*[codes.html, line 5 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxEsJLSQ1GJkx_swRZm:-KxJNJwIL5BVvlNfZ-Mc:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/codes.html#L5)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

The submissions page deals with how to add a code or why a code is there, https://pages.nist.gov/chimad-phase-field/submit_a_new_code/
</blockquote></details>

Done.

---

*[_includes/navbar.html, line 6 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxIv0MiK0FcpvjiDVC-:-KxJNL_j4z5hEM9dlPCG:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/_includes/navbar.html#L6)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

Don't like that, sounds weird, sticking with "Suggested Codes"
</blockquote></details>

Done.

---

*[_includes/navbar.html, line 49 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxIvFbdgQhbVEz2L7Pm:-KxJNMg5JWpQE_Z6ojna:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/_includes/navbar.html#L49)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

as above
</blockquote></details>

Done.

---

*[simulations/index.html, line 29 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxEu8TgzowZxJ-alEBq:-KxJNRMLN87HYKiy-8RH:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/simulations/index.html#L29)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Oh, that's much better.
</blockquote></details>

Done.

---

*[CONTACT.md, line 1 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxEsgHF3tP0I5d2kg3K:-KxJNOh75WbwHACJ2I03:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/CONTACT.md#L1)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

It was committed by mistake, removed now
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by tkphd** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by wd15** [comment]
@tkphd, did I use reviewable correctly? I'm assuming that you and @guyer as reviewers determine whether a discussion is resolved.

**Comment by guyer** [comment]
*[INVOLVEMENT.md, line 9 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxItSFPU5YFcXGo3DQM:-KxJps2-jvz5xsh9yoEA:bbsct2p) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/INVOLVEMENT.md#L9)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I didn't actually mean to to delete the whole sentence, just the word "involving"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by guyer** [comment]
Reviewed 43 of 48 files at r1, 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by guyer** [comment]
Reviewed 1 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Comment by wd15** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[INVOLVEMENT.md, line 9 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516#-KxItSFPU5YFcXGo3DQM:-KxK6Ibpp4UTuhDGFsjw:b44v6jv) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ae2cda5a6b5db7e0dd69588389e8962e158f9764/INVOLVEMENT.md#L9)):*
<details><summary><i>Previously, guyer (Jonathan Guyer) wrote…</i></summary><blockquote>

I didn't actually mean to to delete the whole sentence, just the word "involving"
</blockquote></details>

I think the sentence was stupid. I prefer as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/516)*

**Pull request merged**
