### PR TITLE
Issue487 remove style

### PR DESCRIPTION
**Pull request by wd15**
Remove style elements from HTML and generated HTML files.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/560)

### CODE REVIEW

**Comment by tkphd** [comment]
Hard-coded `font-size` for `flow-text` correctly moved to CSS, which now implements `flow-text comment` for the italic variant. Looks good to me.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[_includes/coffee/simulation.coffee, line 402 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/560#-L-I9g1yQTAZ52zbOC9p:-L-I9g1yQTAZ52zbOC9q:b-sh2ulp) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/4289ef1a7fa8871eab65e1bcd675decd42236a36/_includes/coffee/simulation.coffee#L402)):*
> ```CoffeeScript
>     x: the img selection to add the plotly src to
>   ###
>   style = {format:'svg', height:100, width:100}
> ```

Is this image-size styling hiding somewhere in the CSS, or was it deemed unnecessary?

---

*[js/codes.coffee, line 14 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/560#-L-I90Ib5ZE7EpGvevLC:-L-I90Ib5ZE7EpGvevLD:bw1fmk6) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/75d61abd75893758d394de73e7144100c7caf224/js/codes.coffee#L14)):*
> ```CoffeeScript
>   subselection = selection.filter((d) -> not ("logo" of d))
>   subselection = subselection.append("i").attr("class",
>     "material-icons circle light-green lighen-1")
> ```

`lighen` is a typo, is it not?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/560#-:-L-I88vm0l6whL-7CIYI:b2mj8u5)*

**Comment by wd15** [comment]
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[_includes/coffee/simulation.coffee, line 402 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/560#-L-I9g1yQTAZ52zbOC9p:-L-ICnPeMDwCC3snDPUA:bogubvu) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/4289ef1a7fa8871eab65e1bcd675decd42236a36/_includes/coffee/simulation.coffee#L402)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Is this image-size styling hiding somewhere in the CSS, or was it deemed unnecessary?
</blockquote></details>

Unnecessary, if you look a few lines below that code, you'll see that the Plotly functions have it hardwired.

---

*[js/codes.coffee, line 14 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/560#-L-I90Ib5ZE7EpGvevLC:-L-ID4l1H6gDD1qKR-Nl:buyyh0l) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/75d61abd75893758d394de73e7144100c7caf224/js/codes.coffee#L14)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

`lighen` is a typo, is it not?
</blockquote></details>

Fixed now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/560)*

**Comment by tkphd** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/560)*

**Comment by tkphd** [comment]
Note: Travis-CI build failure is fixed by #572.

**Pull request merged**
