### PR TITLE
Implement scrolling for card overflow

### PR DESCRIPTION
**Pull request by wd15**
Address #531

Fix text overflow on the community and benchmark pages by implementing
scrolling on overflow.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/538)

### CODE REVIEW

**Comment by wd15** [comment]
@stvdwtt, I added you as a reviewer on this as you raised this issue during the chat.

**Comment by tkphd** [comment]
Looks a little derpy in fullscreen now:

screenshot_20171103_153439

**Comment by guyer** [comment]
derpy?

**Comment by stvdwtt** [comment]
@wd15 Oops, just saw the email requesting my review. I'll try to take a look before the end of the day.

I'll see if I get the same extraneous scroll bar as @tkphd with my monitor resolution. I assume that for a large enough window that scroll bar disappears, and that for @tkphd 's window size it just happens to be at the transition from needing a scroll bar and not.

**Comment by wd15** [comment]
@tkphd, @stvdwtt, things should be much better now. The front page should be fully responsive. Try resizing the browser from the widest screen all the way down to the narrowest. Nothing overlaps now for me and the mission statement text looks better as well as the cards.

**Comment by wd15** [comment]
Regarding the scrollbar, I intend for those to kick in at different times on different cards. I don't think that looks bad. I'm more worried about the overlapping title and icons or that the title text can be misaligned at times. That shouldn't happen now.

**Comment by tkphd** [comment]
Looks much better.
- Maybe change the tile aspect ratio to be a little taller than they are wide, so there's room for more verbosity in benchmark summaries and community headlines?
- The Twitter stream has become illegibly tiny at normal (100%) zoom; not sure when that happened.
- The new "Image Links" link shares a frame-type-thing with the Twitter feed, truncating the `#chimadphasefield` tag
- Build problems from Travis-CI:
  - `Liquid Warning: Liquid syntax error (line 1): Expected end_of_string but found string in "{{page.url | replace: '/simulations/', '' | replace: '/' '' }}" in simulations/1a.1.html`, etc.
  - htmlproofer throws `linking to /chimad-phase-field/#benchmarks, but benchmarks does not exist` on numerous instances of `<a href="/chimad-phase-field/#benchmarks" class="navbar-text">Benchmarks</a>`

**Comment by stvdwtt** [comment]
The tiles on the front page look good. Minor nitpick, if it's possible to increase the increase the height of the tiles by the equivalent of one line of the benchmark description (e.g. "Diffusion of solute in a matrix") I think it'd really reduce the occasions when the scrollbars are needed.

Following up on what @tkphd said about the Twitter feed:
- I'm seeing it on the right side of the page now (not sure if that was intentional). As a relatively unimportant component of the page, I think the right side is better than before.
- It is also smaller for me than before.
- It overlaps with the "image links" text for the hexbin, which cuts off the "d" in the hashtag. I'd suggest moving it down.
- Text wrapping around it seems to be improved. Previously,  the twitter feed could cut off the "In January 2015 a group of ..." text. Now that isn't happening.
 
Tiles on the community page:
- Overall look good
- Nitpick: I'm getting scrollbars in 3/8 tiles on the smaller of my monitors. The scrollbars are great as a fallback, but I'd recommend either implementing a (hard? soft?) cap on the text or making them taller

**Comment by wd15** [comment]
On Mon, Nov 6, 2017 at 2:54 PM, Trevor Keller <notifications@github.com> wrote:
>
> Maybe change the tile aspect ratio to be a little taller than they are wide, so there's room for more verbosity in benchmark summaries and community headlines?

I changed the "cards" to medium from small so they are longer now.

> The Twitter stream has become illegibly tiny at normal (100%) zoom; not sure when that happened.

I didn't change the twitter font, but I changed the width. I just
changed the width back to its old width (250px) so should be better
now. BTW, I can see the font just fine on my screen.

> The new "Image Links" link shares a frame-type-thing with the Twitter feed, truncating the #chimadphasefield tag
> Build problems from Travis-CI:

Resolved now.

> Liquid Warning: Liquid syntax error (line 1): Expected end_of_string but found string in "{{page.url | replace: '/simulations/', '' | replace: '/' '' }}" in simulations/1a.1.html, etc.
> htmlproofer throws linking to /chimad-phase-field/#benchmarks, but benchmarks does not exist on numerous instances of <a href="/chimad-phase-field/#benchmarks" class="navbar-text">Benchmarks</a>

Tests pass now.

-- 
Daniel Wheeler

**Comment by wd15** [comment]
On Mon, Nov 6, 2017 at 3:43 PM, Stephen DeWitt <notifications@github.com> wrote:
>
> The tiles on the front page look good. Minor nitpick, if it's possible to increase the increase the height of the tiles by the equivalent of one line of the benchmark description (e.g. "Diffusion of solute in a matrix") I think it'd really reduce the occasions when the scrollbars are needed.

I increased the size of the "cards" by 100px. They come in three sizes
"small", "medium" or "large". I changed them to "medium"
>
> Following up on what @tkphd said about the Twitter feed:
>
> I'm seeing it on the right side of the page now (not sure if that was intentional). As a relatively unimportant component of the page, I think the right side is better than before.

It' s intentional.

> It is also smaller for me than before.

Should be same size now.

> It overlaps with the "image links" text for the hexbin, which cuts off the "d" in the hashtag. I'd suggest moving it down.

Should be fixed.

> Nitpick: I'm getting scrollbars in 3/8 tiles on the smaller of my monitors. The scrollbars are great as a fallback, but I'd recommend either implementing a (hard? soft?) cap on the text or making them taller

Made them taller, but might still scroll at times.

-- 
Daniel Wheeler

**Comment by tkphd** [comment]
Much better, thanks! Is there a way to have the Twitter feed slide down below the Benchmarks when the window shrinks, rather than staying up top alongside the summary? It seems to me like a footnote item, like the chat, rather than headlining information.

**Comment by stvdwtt** [comment]
@wd15 Ah, evidently you just fixed everything I noticed.

Card sizes are great. Twitter pane looks good.

@tkphd I agree about the twitter pane sliding down, if possible

One last comment: the alignment of some of the items looks off -- although perhaps that's baked in to some of the themes
image

**Comment by tkphd** [comment]
@stvdwtt, your attention to detail is admirable.

**Comment by tkphd** [comment]
Jekyll is throwing `ERROR '/chimad-phase-field/js/uploads.js' not found` in my terminal. Not sure if it's a local environment problem or not. `/chimad-phase-field/js/uploads.coffee` exists; do I need to run a converter?

**Comment by tkphd** [comment]
The Twitter feed only slides to the bottom when the window reaches one tile in width. Above that size, it stays alongside the intro text, and produces a lot of whitespace before the `<hr>`.

(Thank you, @wd15, for patiently addressing these stylistic tweaks.)

**Comment by wd15** [comment]
On Mon, Nov 6, 2017 at 4:26 PM, Trevor Keller <notifications@github.com> wrote:
>
> Jekyll is throwing ERROR '/chimad-phase-field/js/uploads.js' not found in my terminal. Not sure if it's a local environment problem or not. /chimad-phase-field/js/uploads.coffee exists; do I need to run a converter?

Kill Jekyll, delete the _site directory and then restart.

-- 
Daniel Wheeler

**Comment by wd15** [comment]
> *edit to add:* Did the font change on the Community page? The tiles look the same size ("small"), but the text looks smaller.

I don't think so. I didn't notice anything.

**Comment by wd15** [comment]
On Mon, Nov 6, 2017 at 4:30 PM, Trevor Keller <notifications@github.com> wrote:
>
> The Twitter feed only slides to the bottom when the window reaches one tile in width. Above that size, it stays alongside the intro text, and produces a lot of whitespace before the <hr>.

At the moment it's sliding down for small windows, <600px. See,

https://github.com/usnistgov/chimad-phase-field/pull/538/files#diff-c3b00db51441fd86cefa204fc593a151R239

I'll switch it to medium and small, <992px. Would that work?

-- 
Daniel Wheeler

**Comment by wd15** [comment]
@tkphd, @stdwtt: latest changes drop the twitter feed to the bottom when screen sizes are less than "xl". The text has been realigned so the mission statement and benchmark text are aligned.

**Comment by tkphd** [comment]
Scrollbars broke on the Community page.

**Comment by wd15** [comment]
I don't believe that we have ever had any scrollbars on the community page. I've created #541 to deal with the responsiveness for the rest of the site. Let's try and merge this pull request and then I'll deal with the other pages.

**Comment by tkphd** [comment]
From the [original PR message](https://github.com/usnistgov/chimad-phase-field/pull/538#issue-271093256):
```
Fix text overflow on the community and benchmark pages by implementing
scrolling on overflow.
```

**Comment by wd15** [comment]
@tkphd, the community page should be fully responsive now. Please review.

**Comment by wd15** [comment]
@stvdwtt, please do give your approval if you're happy with this. Thanks.

**Comment by stvdwtt** [comment]
@wd15 Looks great! Thanks for doing so much fiddling!

**Pull request merged**
