### PR TITLE
Issue452 coffeescript tests

### PR DESCRIPTION
**Pull request by wd15**
Add coffeescript testing using Mocha. The tests are actually run on the compiled Javascript. Going forward this is important as more processing will happen on the frontend.

### CODE REVIEW

**Comment by tkphd** [comment]
```make all``` and ```jekyll build``` return no errors. Is there another command I should be running to test this change?

**Comment by tkphd** [comment]
On [Travis](https://travis-ci.org/usnistgov/chimad-phase-field/builds/287260573?utm_source=github_status&utm_medium=notification), the command ```jekyll build -d ./_site/chimad-phase-field && htmlproofer --check-html --only-4xx --allow-hash-href --empty-alt-ignore --checks-to-ignore ImageCheck ./_site``` returns errors:
> Liquid Warning: Liquid syntax error (line 1): Expected end_of_string but found string in "{{page.url | replace: '/simulations/', '' | replace: '/' '' }}" in simulations/mmsp_1a_wrksttn/index.html

The mocha tests do appear to pass.

**Comment by wd15** [comment]
@tkphd, only need to run the mocha test to check this

**Comment by wd15** [comment]
@tkphd, I don't get the "Liquid: warning" locally, not sure why it's giving a warning on Travis CI. Do you get those warnings locally?

**Pull request merged**
