### PR TITLE
Issue482 welcome statement

### PR DESCRIPTION
**Pull request by tkphd**
Replaces original headline text,
> In January 2015 a group of phase field theorists and code developers met at Northwestern University to discuss ways for the community to improve code collaboration efforts. Everyone agreed that the community needs to become more open and work in a more collaborative manner.
>
> A key factor to improving community code collaboration is to develop resources to compare and contrast phase field codes and libraries. This site aims to provide some of these resources and become a useful web service for phase field practitioners.

with umbrella welcome message,
> Welcome to The Phase Field Community Hub!
>
> If you're a beginner, you'll find resources and a crash course on the technique. If you're an expert, you'll find tools to verify and showcase the quality of your simulations. If you're anywhere in-between, you'll find a community built around shared interest in phase-field and a commitment to opening up our research for the benefit of all.

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/579)

### CODE REVIEW

**Comment by stvdwtt** [comment]
Maybe change "If you're an expert, you'll find tools to verify the quality of your simulations." to "If you're an expert, you'll find tools to verify/showcase the quality of your simulations."

I think a good carrot for contributions is the opportunity to show how great the code you've been spending months/years on is.

**Comment by drjamesawarren** [comment]
I like all of these changes and am glad to see the invitation to join the gang:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/579#-:-L-cX7k1sEsf67V3iDKb:b2v4twp)*

**Comment by wd15** [comment]
@tkphd, tests need fixing

**Comment by wd15** [comment]
@tkphd, tests fixed themselves

**Comment by wd15** [comment]
@tkphd, one thing, we don't actually have any text for beginners currently so the text isn't really true as it stands

**Comment by tkphd** [comment]
Agreed. It's aspirational, and I'll file some issues to address the deficit. Let's change the site to fit the vision, not vice-versa.

**Comment by wd15** [comment]
Suggestions from Olle:

> Welcome to the Phase Field Hub and to our phase field community. If you're a beginner, you'll find resources and a crash course on the technique. If you're an expert, you'll find tools to verify the quality of your simulations. If you're anywhere in-between, you'll find a community built around shared interest in phase-field and a commitment to opening up our research for the benefit of all.


> The Phase Field Hub contains information about phase field modeling in general, workshops, benchmark problems for phase field modeling, how to participate in gitter chats, and other information that may help you engage in the phase field community.
> 
> Some links:
> 
> • What is Phase Field modeling? Introduction, crash course, glossary, references,
> • Calendar – workshops, conferences.
> • Gitter chat
> • Phase Field Benchmark Problems
> • Phase Field Codes

**Comment by drjamesawarren** [comment]
I’d not put the calendar thing in there unless we decide to actively maintain it.

**Comment by wd15** [comment]
I think we should use the following (incorporating a change from Olle):

> Welcome to the Phase Field Community Hub.  If you're a beginner, you'll find resources and a crash course on the technique. If you're an expert, you'll find tools to verify and showcase the quality of your simulations.  If you're anywhere in-between, you'll find a community built around a shared interest in phase-field and a commitment to opening up our research for the benefit of all.

I think that we need to work on making links more prominent in a sidebar rather than adding them as a list below this text.

**Pull request merged**
