### PR TITLE
implement landing page for each simulation

### PR DESCRIPTION
**Pull request by wd15**
Look at test_lander as the best example of a variety of data

### CODE REVIEW

**Comment by tkphd** [comment]
On simulations/test_lander, the figure captions never extend beyond one line. Is this because the text ran out, or because the caption functionality is broken? Can we wrap the caption text inside figure-boxes?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/408#-:-KtIEWOFgNsbN0UbjAHH:b-9veel4)*

**Comment by wd15** [comment]
@tkphd, I limited the display text to be only one line so it's like a title. Unfortunately the cards don't expand. I'll work on improving that though, but it's quite tricky

**Comment by tkphd** [comment]
Reviewed 124 of 124 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[_data/migrate_yaml.py, line 68 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/408#-KtIGFpz6J7Z3me_T86b:-KtIGFpz6J7Z3me_T86c:boa0vdh) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/55b52018fd917c2e8cc040f425e6d98e7ba8ca8e/_data/migrate_yaml.py#L68)):*
> ```Python
> 
> if __name__ == '__main__':
>     # migrate(
> ```

Crufty comments, but OK.

---

*[_includes/essential.coffee, line 5 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/408#-KtII0nIdaR7ujmkFyQ3:-KtII0nIdaR7ujmkFyQ4:b-9fdhb9) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/55b52018fd917c2e8cc040f425e6d98e7ba8ca8e/_includes/essential.coffee#L5)):*
> ```CoffeeScript
> # @author Cedric Ruiz
> # @license MIT
> ###
> ```

Link to the original source, https://github.com/elclanrs/essential.js

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/408)*

**Comment by tkphd** [comment]
The test landing page looks great! I have a couple insignificant comments on the source, but this looks ready to merge. Or are you still tinkering?

**Comment by wd15** [comment]
@tkphd, I'm still tinkering. I will merge when I'm ready now that you've given the all clear.

I've added your comments as tickets on the project page, which I'll include in the next pull request.

**Comment by tkphd** [comment]
Cool. Nice work.

**Pull request merged**
