### PR TITLE
HiPerC

### PR DESCRIPTION
**Pull request by tkphd**
**Add images and rename HiPerC results**

Migrate data from gist.github.com to backblaze.com and osf.io.

These changes can be [viewed live][live-site].

**Remember to tear down the [live site][live-site] when merging or
  closing this pull-request.**

[live-site]: http://random-cat-604.surge.sh

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/604)

### CODE REVIEW

**Comment by wd15** [comment]
@tkphd, I made a pull request into your branch, the only relevant change is https://github.com/tkphd/chimad-phase-field/pull/1/files#diff-bf7e06546eac28ed03bb7d8ddade6f66. The Backblaze2 links actually work. It seems that the problem was just the transformation. The OSF download doesn't work though.

**Comment by wd15** [comment]
@tkphd, I closed the pull request, not necessary, I'll just point out the changes on reviewable.

**Comment by wd15** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[_data/simulations/hiperc_1b_cuda/meta.yaml, line 36 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/604#-L0oiE3NLRFU5b-QmK9i:-L0oiE3OFWwGl6NqCqYZ:b-4wxv2s) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ba02320f84588f87b086f86801456dc9708e44d0/_data/simulations/hiperc_1b_cuda/meta.yaml#L36)):*
> ```YAML
>   - name: free_energy
>     type: line
>     url: https://f001.backblazeb2.com/file/hiperc-results/gpu-cuda-spinodal/free-energy-9pt.csv
> ```

Blaze links actually work

---

*[_data/simulations/hiperc_1b_cuda/meta.yaml, line 48 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/604#-L0ohvttX8Nal2VB-xXS:-L0ohvttX8Nal2VB-xXT:bu71xd2) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ba02320f84588f87b086f86801456dc9708e44d0/_data/simulations/hiperc_1b_cuda/meta.yaml#L48)):*
> ```YAML
>         type: formula
>       - as: x
>         expr: datum.time
> ```

Change to `datum.sim_time`

---

*[_data/simulations/hiperc_1b_cuda_9pt/meta.yaml, line 36 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/604#-L0oi7mcaUlCDtNffrrI:-L0oi7mcaUlCDtNffrrJ:b20n30g) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ba02320f84588f87b086f86801456dc9708e44d0/_data/simulations/hiperc_1b_cuda_9pt/meta.yaml#L36)):*
> ```YAML
>   - name: free_energy
>     type: line
>     url: https://osf.io/5pef2/download
> ```

OSF downloads aren't working - they give a CORS error.

---

*[_data/simulations/hiperc_1b_cuda_9pt/meta.yaml, line 48 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/604#-L0oi4vXp28KjjXHlRD0:-L0oi4vXp28KjjXHlRD1:b-mrsooi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ba02320f84588f87b086f86801456dc9708e44d0/_data/simulations/hiperc_1b_cuda_9pt/meta.yaml#L48)):*
> ```YAML
>         type: formula
>       - as: x
>         expr: datum.time
> ```

Change to `datum.time`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/604)*

**Comment by wd15** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[_data/simulations/hiperc_1b_cuda_9pt/meta.yaml, line 48 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/604#-L0oi4vXp28KjjXHlRD0:-L0oiRBGoFp3HgcPrDx8:b452dgx) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ba02320f84588f87b086f86801456dc9708e44d0/_data/simulations/hiperc_1b_cuda_9pt/meta.yaml#L48)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

Change to `datum.time`
</blockquote></details>

`datum.sim_time`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/604)*

**Comment by tkphd** [comment]
Reviewed 9 of 13 files at r2, 2 of 4 files at r3.
Review status: 11 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[_data/simulations/hiperc_1b_cuda/meta.yaml, line 36 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/604#-L0oiE3NLRFU5b-QmK9i:-L0uqTEPy1yomG6-UKt4:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ba02320f84588f87b086f86801456dc9708e44d0/_data/simulations/hiperc_1b_cuda/meta.yaml#L36)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

Blaze links actually work
</blockquote></details>

Done.

---

*[_data/simulations/hiperc_1b_cuda/meta.yaml, line 48 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/604#-L0ohvttX8Nal2VB-xXS:-L0uqSthX9YPZ_EEZwHZ:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ba02320f84588f87b086f86801456dc9708e44d0/_data/simulations/hiperc_1b_cuda/meta.yaml#L48)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

Change to `datum.sim_time`
</blockquote></details>

Done.

---

*[_data/simulations/hiperc_1b_cuda_9pt/meta.yaml, line 36 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/604#-L0oi7mcaUlCDtNffrrI:-L0uqWftLQvz8pg9wBUo:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ba02320f84588f87b086f86801456dc9708e44d0/_data/simulations/hiperc_1b_cuda_9pt/meta.yaml#L36)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

OSF downloads aren't working - they give a CORS error.
</blockquote></details>

Done.

---

*[_data/simulations/hiperc_1b_cuda_9pt/meta.yaml, line 48 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/604#-L0oi4vXp28KjjXHlRD0:-L0uqW1fR9mDwFPYCKr0:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/ba02320f84588f87b086f86801456dc9708e44d0/_data/simulations/hiperc_1b_cuda_9pt/meta.yaml#L48)):*
<details><summary><i>Previously, wd15 (Daniel Wheeler) wrote…</i></summary><blockquote>

`datum.sim_time`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/604)*

**Pull request merged**
