### PR TITLE
Issue548 openphase

### PR DESCRIPTION
**Pull request by wd15**
Add OpenPhase to the suggested list of codes, see http://www.openphase.de/index.html

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/549)

### CODE REVIEW

**Comment by tkphd** [comment]
The checked-in logo truncates "OpenPhase" to "OpenPh", which is not the correct styling. Everything else looks good.

**Comment by wd15** [comment]
I reduced the cropping of the open phase logo and made it fit the image circle somewhat better

**Comment by tkphd** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/549)*

**Comment by tkphd** [comment]
We should perhaps sort the suggested codes alphabetically, or by number of users, or age, or... ?

**Comment by stvdwtt** [comment]
@tkphd This could be a bit of a pain, but I think the ideal ordering would be based on what fraction of the benchmark problem parts the code has submissions for (and alphabetical or age beyond that).

**Comment by wd15** [comment]
@stvdwtt, @tkphd: see #443. Eventually, we can have a badge based on number of uploads, which can also be used to sort.

**Pull request merged**
