### PR TITLE
Update mailing list page to point at new one

### PR DESCRIPTION
**Pull request by wd15**
Address #540

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/544)

### CODE REVIEW

**Comment by tkphd** [comment]
Is https://list.nist.gov accessible to the public? I can't reach it from home.

**Comment by wd15** [comment]
On Wed, Nov 8, 2017 at 9:51 AM, Trevor Keller <notifications@github.com> wrote:
>
> Is https://list.nist.gov accessible to the public? I can't reach it from home.

You're right, nice spot. The link is
https://groups.google.com/a/list.nist.gov/forum/#!forum/chimad-phase-field.
I'm going to email the admins to see why https://list.nist.gov isn't
working, but in the meantime I'll change it to the long address.

-- 
Daniel Wheeler

**Comment by wd15** [comment]
The "list.nist.gov" server is still under review at NIST so isn't available yet.

**Comment by tkphd** [comment]
Yep, the long address works. Thanks.

**Pull request merged**
