### PR TITLE
Links to hackathon spec 3 and 4 on front page

### PR DESCRIPTION
**Pull request by wd15**
Address #423 

**Note that jekyll-redirect-from plugin is now required**

 - add links to specs 3 and 4 on front page
 - improve look of the cards
 - improve representation of benchmark collection of data

built off #516 so includes the commits from that pull request (#516 should be merged first)

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/522)

### CODE REVIEW

**Comment by tkphd** [comment]
*[CONTACT.md, line 2 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/522#-KxUOaNxVEecQf93h5Ap:-KxUOaNxVEecQf93h5Aq:b-hbmvsc) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/779e9b2f46971e41d3f51f71177fb9163409d1e0/CONTACT.md#L2)):*
> ```Markdown
> ---
> title: "About CHiMad Phase Field"
> ```

Was this file accidentally committed again? It looks like I'm reviewing the same stuff again...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/522)*

**Comment by tkphd** [comment]
Reviewed 82 of 82 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[_includes/test.coffee, line 41 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/522#-KxUPLfi2zsHzx6SgPO3:-KxUPLfi2zsHzx6SgPO4:bgc1zql) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/779e9b2f46971e41d3f51f71177fb9163409d1e0/_includes/test.coffee#L41)):*
> ```CoffeeScript
> 
> 
> it('test count_uploads', ->
> ```

Does this need updating for the new benchmarks, or do we need uploads first?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/522)*

**Comment by tkphd** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/522#-:-KxUQLeqLXU2hxm_irJH:bnfp4nl)*

**Comment by wd15** [comment]
Review status: 38 of 39 files reviewed at latest revision, 2 unresolved discussions.

---

*[CONTACT.md, line 2 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/522#-KxUOaNxVEecQf93h5Ap:-KxUbL8qp122u_Y9GCAu:bqoua0b) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/779e9b2f46971e41d3f51f71177fb9163409d1e0/CONTACT.md#L2)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Was this file accidentally committed again? It looks like I'm reviewing the same stuff again...
</blockquote></details>

I merged in master due to conflicts and this is gone now.

---

*[_includes/test.coffee, line 41 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/522#-KxUPLfi2zsHzx6SgPO3:-KxUbpDyZWjE2TPf9pg-:bdg8mf2) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/779e9b2f46971e41d3f51f71177fb9163409d1e0/_includes/test.coffee#L41)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Does this need updating for the new benchmarks, or do we need uploads first?
</blockquote></details>

I'm rather confused by your question. This is just a small test case for a function called count_uploads, which counts uploads for a given benchmark. It has nothing to do with new benchmarks. It will work for any benchmark. The data is just sample data for the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/522)*

**Comment by tkphd** [comment]
Reviewed 2 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/522)*

**Comment by wd15** [comment]
@tkphd, I think you still need to approve the pull request.

**Comment by tkphd** [comment]
It's up-to-date in Reviewable: my big green button says "Merge." I can approve it in the GitHub review tool if you like. I think our workflow deviates slightly in the last step from the typical case, in that you have been merging your own PRs after receiving approval from the rest of us. Typically, I would "approve" by merging your PR into master. But your point is taken: Reviewable does not make it obvious that the code has been approved, especially when there are multiple reviewers on the case. Something to look into and file an issue about.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/522#-:-Kxi8MTPKImhMUXzVGjp:bk7ajxv)*

**Comment by tkphd** [comment]
Approved using the GitHub tool, but it's super annoying to have to use both when Reviewable covers everything else. Reading through their [gitter](https://gitter.im/Reviewable/Reviewable) backlog for ideas.

**Comment by wd15** [comment]
@tkphd, I think our current workflow is good in the case where there is a single main developer. It doesn't matter too much either way. I'm happy for you to merge pull requests from reviewable if you want to.

**Comment by tkphd** [comment]
From gitter, it seems Reviewable deliberately doesn't implement an "approve" or "required reviewer" functionality. Instead, they choose to depend upon the "assign" functionality built in to github: after review, when I assign it back to you, it's ready for you to address comments or, if the last comment was "lgtm" or :+1:, then merge it.

Looks like we need to document Reviewable in our Contributing docs.

**Pull request merged**
