### PR TITLE
Updates to the "Development" page

### PR DESCRIPTION
**Pull request by stvdwtt**
Edits from issue #496

### CODE REVIEW

**Comment by stvdwtt** [comment]
For some reason I couldn't get bullets to work. I tried using +,-, and * as well as various whitespace. The markdown is parsed with Kramdown, isn't it?

**Comment by tkphd** [comment]
From the [Github rendering](https://github.com/stvdwtt/chimad-phase-field/blob/update_dev_page/DEVELOPMENT.md), it seems that some of your links are malformed. This might be throwing it off. I would recommend iterating on this as a [gist](https://gist.github.com), to make sure the formatting is up to your standards. Once you're happy with Github's, we can try to make Kramdown render it correctly. Or, write the lists using html tags,
```
<ul>
  <li>your</li>
  <li>text</li>
  <li>here</li>
</ul>
```

**Comment by stvdwtt** [comment]
@tkphd Yeah, I'm not sure why the links aren't showing up correctly in GitHub, however on my local build of the site the links are showing up properly. Alternatively, the bullets do show up in the GitHub rendering, but not on my local build of the site.

I tried to make the lists with the html tags as you suggested and that worked to generate bullets on my local markdown parser (just like using '-'s did), but once again doesn't show up as a list on my local build of the site.

**Comment by stvdwtt** [comment]
I’ll continue to look into it. I think the page functions/looks fine without the bullets, so that can be something I can fix later on.

**Comment by wd15** [comment]
@stvdwtt, I fixed the issue with bullet points. It was a CSS problem. I also updated the dev instructions for the community page which are now wrong. Thanks for your contribution, it looks much better.

**Comment by stvdwtt** [comment]
Great! Thanks for figuring that out

**Pull request merged**
