### PR TITLE
Issue552 doi schema

### PR DESCRIPTION
**Pull request by wd15**
Add script to generate DOI data to be used by NIST librarian to generate DOIs for each simulation. This will be automated via an API in the future.

This change is [Reviewable](https://reviewable.io/reviews/usnistgov/chimad-phase-field/554)

### CODE REVIEW

**Comment by tkphd** [comment]
Reviewed 44 of 58 files at r1.
Review status: 44 of 58 files reviewed at latest revision, 14 unresolved discussions.

---

*[_data/simulations/moose_1a_ia/meta.yaml, line 33 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0ge5_SNjtQCT11aIT:-Kz0ge5aTJEEP582DSVf:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_1a_ia/meta.yaml#L33)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_1b_ia/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gkHS-uS-FywJgWr3:-Kz0gkHT_AisG2le-Yng:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_1b_ia/meta.yaml#L34)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_1b_sta/meta.yaml, line 33 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0glQ1ZndL9gK9JjN9:-Kz0glQ1ZndL9gK9JjNA:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_1b_sta/meta.yaml#L33)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_1c_ia/meta.yaml, line 33 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gmZjCxj3FWA_z0Tl:-Kz0gmZjCxj3FWA_z0Tm:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_1c_ia/meta.yaml#L33)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_1d_ia/meta.yaml, line 33 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gnGUbGgIkbm5yzHo:-Kz0gnGUbGgIkbm5yzHp:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_1d_ia/meta.yaml#L33)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_1d_sta/meta.yaml, line 33 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0go5RqGg62C6trQ8S:-Kz0go5RqGg62C6trQ8T:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_1d_sta/meta.yaml#L33)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_2a_ia/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0goxAWAjrxHd1cHxl:-Kz0goxAWAjrxHd1cHxm:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2a_ia/meta.yaml#L34)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_2a_sta/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gpbGLrUZ-JoR07OM:-Kz0gpbGLrUZ-JoR07ON:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2a_sta/meta.yaml#L34)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_2b_ia/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gqJE2ProslNQMmOT:-Kz0gqJE2ProslNQMmOU:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2b_ia/meta.yaml#L34)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_2b_sta/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gqy74vCQ5UQmoF5O:-Kz0gqy74vCQ5UQmoF5P:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2b_sta/meta.yaml#L34)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_2c_ia/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0grfMtni_SIVH9a5l:-Kz0grfNDnNn3EsJFCQ0:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2c_ia/meta.yaml#L34)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_2c_sta/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gsGUQdbYT1yUwZpr:-Kz0gsGUQdbYT1yUwZps:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2c_sta/meta.yaml#L34)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_2d_ia/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gswLR3qhK7nBZuUF:-Kz0gswLR3qhK7nBZuUG:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2d_ia/meta.yaml#L34)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---

*[_data/simulations/moose_2d_sta/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gtdsb1Qv6nYIgBrQ:-Kz0gtdsb1Qv6nYIgBrR:b-6ritqi) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2d_sta/meta.yaml#L34)):*
> ```YAML
> metadata:
>   author:
>     first: Andrea
> ```

The author provided A. M., not Andrea. Please revert.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554)*

**Comment by wd15** [comment]
@tkphd, some have "Andrea" and some had "A. M.". I was trying to be consistent so that the author uses a consistent name.

**Comment by tkphd** [comment]
All of the changed files had "A. M. Jokisaari" in the `author` field, now they all have "Andrea" in the `first` field. The consistent change would set
```
  first: A. M.
  last: Jokisaari
```

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-:-Kz0miYetgtANK73Xe_v:bpwu9ah)*

**Comment by wd15** [comment]
@tkphd, Andrea has previously used both Andrea and A. M. for different uploads and so I was making it consistent. For example, see,

https://github.com/usnistgov/chimad-phase-field/blob/master/_data/simulations/coral_6a/meta.yaml#L3

**Comment by wd15** [comment]
Review status: 42 of 58 files reviewed at latest revision, 14 unresolved discussions.

---

*[_data/simulations/moose_1a_ia/meta.yaml, line 33 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0ge5_SNjtQCT11aIT:-KzA4fd2pWfAlsztz3_j:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_1a_ia/meta.yaml#L33)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

The author provided A. M., not Andrea. Please revert.
</blockquote></details>

Done.

---

*[_data/simulations/moose_1b_ia/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gkHS-uS-FywJgWr3:-KzA4gLDwFdPw-AZlUfX:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_1b_ia/meta.yaml#L34)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

The author provided A. M., not Andrea. Please revert.
</blockquote></details>

Done.

---

*[_data/simulations/moose_1b_sta/meta.yaml, line 33 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0glQ1ZndL9gK9JjN9:-KzA4hDFDxGMk3h4rtaT:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_1b_sta/meta.yaml#L33)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

The author provided A. M., not Andrea. Please revert.
</blockquote></details>

Done.

---

*[_data/simulations/moose_1c_ia/meta.yaml, line 33 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gmZjCxj3FWA_z0Tl:-KzA4hqtVYQjqgDVVXhB:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_1c_ia/meta.yaml#L33)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

The author provided A. M., not Andrea. Please revert.
</blockquote></details>

Done.

---

*[_data/simulations/moose_1d_ia/meta.yaml, line 33 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gnGUbGgIkbm5yzHo:-KzA4iVLcJ9wDITJX_rU:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_1d_ia/meta.yaml#L33)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

The author provided A. M., not Andrea. Please revert.
</blockquote></details>

Done.

---

*[_data/simulations/moose_2a_sta/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gpbGLrUZ-JoR07OM:-KzA4kPz1uyuM3q0NxHH:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2a_sta/meta.yaml#L34)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

The author provided A. M., not Andrea. Please revert.
</blockquote></details>

Done.

---

*[_data/simulations/moose_2b_ia/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gqJE2ProslNQMmOT:-KzA4kwcplUb2rp2P8q5:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2b_ia/meta.yaml#L34)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

The author provided A. M., not Andrea. Please revert.
</blockquote></details>

Done.

---

*[_data/simulations/moose_2b_sta/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gqy74vCQ5UQmoF5O:-KzA4lYU11wTcxEPzGoX:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2b_sta/meta.yaml#L34)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

The author provided A. M., not Andrea. Please revert.
</blockquote></details>

Done.

---

*[_data/simulations/moose_2c_sta/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gsGUQdbYT1yUwZpr:-KzA4n2D76j5uduTmc2N:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2c_sta/meta.yaml#L34)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

The author provided A. M., not Andrea. Please revert.
</blockquote></details>

Done.

---

*[_data/simulations/moose_2d_ia/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gswLR3qhK7nBZuUF:-KzA4ngVFCqehTcTZd9B:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2d_ia/meta.yaml#L34)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

The author provided A. M., not Andrea. Please revert.
</blockquote></details>

Done.

---

*[_data/simulations/moose_2d_sta/meta.yaml, line 34 at r1](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-Kz0gtdsb1Qv6nYIgBrQ:-KzA4oCSbaWAENMdNPud:b-896fix) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/11ed46784cf024e336d0364ce539fdf51833c504/_data/simulations/moose_2d_sta/meta.yaml#L34)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

The author provided A. M., not Andrea. Please revert.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554)*

**Comment by tkphd** [comment]
Reviewed 15 of 16 files at r2.
Review status: 57 of 58 files reviewed at latest revision, 4 unresolved discussions.

---

*[_data/migrate_yaml.py, line 68 at r2](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-KzAOnZVIB8y4R428efX:-KzAOnZWcXXdAMXeNWZ7:b-n03hjz) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/b6fee93488df3df26281274e72329bcd3a9dad68/_data/migrate_yaml.py#L68)):*
> ```Python
> 
> if __name__ == '__main__':
>     def migrate_f(data):
> ```

Clever, but not sure it needs to be checked into the repo. What happens if another user with the same first name submits a result?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554)*

**Comment by wd15** [comment]
Review status: 57 of 58 files reviewed at latest revision, 4 unresolved discussions.

---

*[_data/migrate_yaml.py, line 68 at r2](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554#-KzAOnZVIB8y4R428efX:-KzAtC3kccsmV_iniD6s:b-5amlr6) ([raw file](https://github.com/usnistgov/chimad-phase-field/blob/b6fee93488df3df26281274e72329bcd3a9dad68/_data/migrate_yaml.py#L68)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Clever, but not sure it needs to be checked into the repo. What happens if another user with the same first name submits a result?
</blockquote></details>

This file isn't ever run automatically. The `migrate_f` function needs to be rewritten every time a migration is done. This is just a standalone utility script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/usnistgov/chimad-phase-field/554)*

**Pull request merged**
